export {default as AthleteInfo} from './AthleteInfo'
export {default as EventsAll} from './EventsAll'
export {default as Goals} from './Goals'
export {default as Settings} from './Settings'
export {default as Statistics} from './Statistics'
export {default as Notes} from './Notes'